name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      
      PYTHONPATH: src

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Install dev tools
        run: |
          pip install --no-cache-dir \
            black flake8 pytest httpx python-multipart

      - name: Check formatting with Black
        run: |
          black --check src tests

      - name: Lint with flake8
        run: |
          flake8 src tests \
            --max-line-length=120 \
            --ignore=E231,E302,E303,W293

      - name: Run pytest
        run: |
          pytest -q

      - name: Build Docker image
        run: |
          docker build -t object-detection-service:ci .
